apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: app-prod
data:
  SPRING_PROFILES_ACTIVE: "prod"
  LOG_LEVEL: "INFO"
  MAX_UPLOAD_SIZE_MB: "50"
  TIMEOUT_MS: "30000"
  CORS_ALLOWED_ORIGINS: "https://api.team5-ingress.indonesiacentral.cloudapp.azure.com,https://app.team5-ingress.indonesiacentral.cloudapp.azure.com"
