apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: app-prod
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:sqlserver://team5-sqlserver.database.windows.net:1433;databaseName=team5-db"
  DB_USER: "azure"
  DB_PASSWORD: "YourSecurePassword123!"
  JWT_SECRET: "ChangeThisToStrongSecretKey"
