apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeSelector:
        agentpool: usernode
      containers:
      - name: frontend
        image: xdn73/frontend:v3
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: frontend-config

        # 👇 mount nginx config from same ConfigMap
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"

      # 👇 volume definition (same ConfigMap)
      volumes:
      - name: nginx-config
        configMap:
          name: frontend-config
