apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unified-app-ingress
  namespace: app-prod
  annotations:
  
    nginx.ingress.kubernetes.io/use-regex: "true" 
  
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx 
  rules:
  #- host: team5-ingress.indonesiacentral.cloudapp.azure.com
    http:
      paths:
      
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific 
        backend:
          service:
            name: backend-svc 
            port:
              number: 8080
      
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-svc
            port:
              number: 80