name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - terraform-infra-ftoon
  pull_request:
    branches:
      - terraform-infra-ftoon
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Pipeline
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Import RG
        run: terraform import -var="location=East US" azurerm_resource_group.rg "/subscriptions/80646857-9142-494b-90c5-32fea6acbc41/resourceGroups/team5-rg" || echo "RG already managed"

      - name: Terraform Import VNet
        run: terraform import -var="location=East US" azurerm_virtual_network.vnet "/subscriptions/80646857-9142-494b-90c5-32fea6acbc41/resourceGroups/team5-rg/providers/Microsoft.Network/virtualNetworks/team5-vnet" || echo "VNet already managed"

      - name: Terraform Import SQL
        run: terraform import -var="location=East US" azurerm_mssql_server.sql "/subscriptions/80646857-9142-494b-90c5-32fea6acbc41/resourceGroups/team5-rg/providers/Microsoft.Sql/servers/team5-sqlserver" || echo "SQL Server already managed"

      - name: Terraform Import KeyVault
        run: terraform import -var="location=East US" azurerm_key_vault.kv "/subscriptions/80646857-9142-494b-90c5-32fea6acbc41/resourceGroups/team5-rg/providers/Microsoft.KeyVault/vaults/team5-kv" || echo "KeyVault already managed"

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        run: terraform apply -auto-approve

#
