name: Terraform Pipeline

on:
  push:
    branches:
      - terraform-infra-ftoon
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Pipeline
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Import RG
        run: |
          terraform import -var="location=East US" module.rg.azurerm_resource_group.this "/subscriptions/80646857-9142-494b-90c5-32fea6acbc41/resourceGroups/team5-rg" || echo "RG already managed"

      - name: Terraform Import VNet
        run: |
          terraform import -var="location=East US" module.vnet.azurerm_virtual_network.this "/subscriptions/80646857-9142-494b-90c5-32fea6acbc41/resourceGroups/team5-rg/providers/Microsoft.Network/virtualNetworks/team5-vnet" || echo "VNet already managed"

      - name: Terraform Import SQL
        run: |
          terraform import -var="location=East US" module.sql.azurerm_mssql_server.this "/subscriptions/80646857-9142-494b-90c5-32fea6acbc41/resourceGroups/team5-rg/providers/Microsoft.Sql/servers/team5-sqlserver" || echo "SQL Server already managed"

      - name: Terraform Import KeyVault
        run: |
          terraform import -var="location=East US" module.keyvault.azurerm_key_vault.this "/subscriptions/80646857-9142-494b-90c5-32fea6acbc41/resourceGroups/team5-rg/providers/Microsoft.KeyVault/vaults/team5-kv" || echo "KeyVault already managed"

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        run: terraform apply -auto-approve
